### ISSUE TITLE
Bugs and Feedback - continuous collection of product backlog items

### ISSUE THREAD

**Issue by WolfgangKoe** [MichiSpebach/mammutmap#1]
Es gibt noch merkwürdige Abstände im Raster

![Bugfix_Abstaende_Raster](https://user-images.githubusercontent.com/29704832/167786110-4a6be3f0-1ac5-40f5-84dd-72b9ac537de9.jpg)

**Comment by WolfgangKoe** [comment]
Der Text in einer Datei wird nicht angezeigt, wenn der Text zu lang ist. 

![Bugfix_Text_File_zu_gross](https://user-images.githubusercontent.com/29704832/167788098-640644eb-0586-48b0-a104-7063a4fddbc9.JPG)

**Comment by WolfgangKoe** [comment]
Features für die einfachere Benutzung:

1. Mehrere Dateien oder Ordner via "Shift + left klick" markieren und gleichzeitig verschieben können.

2. Wichtige Ordner (z.B. "src") könnten von Anfang an größer als andere Ordner und Dateien (z.B. Config-Dateien) dargestellt werden. Bisher ist alles gleich groß. Entsprechend auch für Unterordner.

3. Default-Darstellung: Ist "quadratisch" oder "rechteckig" besser?

**Comment by MichiSpebach** [comment]
> Es gibt noch merkwürdige Abstände im Raster
> 
> ![Bugfix_Abstaende_Raster](https://user-images.githubusercontent.com/29704832/167786110-4a6be3f0-1ac5-40f5-84dd-72b9ac537de9.jpg)

werden ich verbessern, die abstände im raster sollten alle gleich sein.

**Comment by MichiSpebach** [comment]
> Der Text in einer Datei wird nicht angezeigt, wenn der Text zu lang ist.
> 
> ![Bugfix_Text_File_zu_gross](https://user-images.githubusercontent.com/29704832/167788098-640644eb-0586-48b0-a104-7063a4fddbc9.JPG)

Das rendern von DateiInhalten ist noch sehr ineffizient implementiert, deshalb gibt es diese Sperre um lags zu verhindern. Im Backlog ist das relativ weit unten weil es bisjetzt viele Dinge mit höherer Priorität gibt.

**Comment by MichiSpebach** [comment]
>     1. Mehrere Dateien oder Ordner via "Shift + left klick" markieren und gleichzeitig verschieben können.
Gute Idee

>     2. Wichtige Ordner (z.B. "src") könnten von Anfang an größer als andere Ordner und Dateien (z.B. Config-Dateien) dargestellt werden. Bisher ist alles gleich groß. Entsprechend auch für Unterordner.
Aufwändig automatisiert zu entscheiden welche Ordner größer dargestellt werden sollen. Auch gibt es das Problem nur wenn man das Projekt zum ersten mal aufmacht, sobald man die größe eines Ordners anpasst wird sie gespeichert.

>     3. Default-Darstellung: Ist "quadratisch" oder "rechteckig" besser?
Ich arbeite daran den RootOrdner in seiner Größe ändern zu können, dadurch lässt sich das Problem ziemliche einfach beheben.

Wir sollten irgendwann aus diesen Issues einzelne Issue-Seiten erstellen.

**Comment by MichiSpebach** [comment]
> > Es gibt noch merkwürdige Abstände im Raster
> > ![Bugfix_Abstaende_Raster](https://user-images.githubusercontent.com/29704832/167786110-4a6be3f0-1ac5-40f5-84dd-72b9ac537de9.jpg)
> 
> werden ich verbessern, die abstände im raster sollten alle gleich sein.

done, es werden jetzt aller 4er Linien angezeigt (auch die 48er und 52er), die 50er Linie ist aber erstmal noch da, weil das die Mitte ist.

**Comment by MichiSpebach** [comment]
> > ```
> > 3. Default-Darstellung: Ist "quadratisch" oder "rechteckig" besser?
> > ```
> 
> Ich arbeite daran den RootOrdner in seiner Größe ändern zu können, dadurch lässt sich das Problem ziemliche einfach beheben.

done

**Comment by MichiSpebach** [comment]
> Wir sollten irgendwann aus diesen Issues einzelne Issue-Seiten erstellen.

Aus den Issues die noch nicht abgeschlossen sind, sind einzelne erstellt, wenn die Abgeschlossenen noch Verbesserungspotenzial haben, dann einfach neue Issues anlegen.
