### ISSUE TITLE
Sind die "Link nodes" nicht löschbar?

### ISSUE THREAD

**Issue by WolfgangKoe** [MichiSpebach/mammutmap#3]

**Comment by MichiSpebach** [comment]
ich arbeite daran, die link nodes sind noch nicht fertig. ich gebe hier über den status bescheid.

**Comment by MichiSpebach** [comment]
![grafik](https://user-images.githubusercontent.com/102001655/230620082-0387588b-4887-44ea-9621-fb4fb9590bf8.png)

entry point to implement it would be `src/core/contextMenu.ts` and `src/core/node/NodeWidget.ts` (`NodeWidget` will be renamed to `LinkNodeWidget` at some point later)
![grafik](https://user-images.githubusercontent.com/102001655/230620822-189821a2-9bec-409d-a33f-c23e5274334a.png)

**Comment by MichiSpebach** [comment]
this is done now, adjacent/bordering links are also handled
