### ISSUE TITLE
Ordner

### ISSUE THREAD

**Issue by WolfgangKoe** [MichiSpebach/mammutmap#9]
Ordner mit vielen Subordnern, die für die Visualisierung der Systemstruktur zunächst unerheblich sind, führen schnell zum Absturz von mammutmap. Gibt es eine Möglichkeit Ordner oder Dateien gezielt auszublenden, dass sie bzw. deren Inhalte nicht gerendert werden?

![image](https://user-images.githubusercontent.com/29704832/173294237-ade90cd6-88f5-4fbc-aacf-0226e052b1df.png)

**Comment by MichiSpebach** [comment]
Das rendern ist noch nicht sehr effizient implementiert, ich habe jetzt eingebaut dass man bei Ordnern mit mehr als 200 Subordnern/Dateien gefragt wird ob man diese wirklich rendern will:
![image](https://user-images.githubusercontent.com/102001655/174392478-ec031edc-fb4d-45f7-9a81-304539e06c21.png)
